### ISSUE TITLE
Can't run the app

### ISSUE THREAD

**Issue by julianmojico** [chadeyrasal/local-fruits-veg#5]
I got this error while following the readme instructions. Not really familiar with ruby and bundler though.

`LoadError: Error loading the 'sqlite3' Active Record adapter. Missing a gem it depends on? can't activate sqlite3 (~> 1.4), already activated sqlite3-1.3.13. Make sure all dependencies are added to Gemfile.`

Is there any place I can see you app live and running?
 Thanks

**Comment by jmojico** [comment]
I realized I was running npm using node 8 and latest is 12.
nvm install --lts solved the issue.

**Comment by chadeyrasal** [comment]
Should be fine now. 
Otherwise you can find a demo [here](https://www.youtube.com/watch?v=eiv1EZhU7UI)
